Aerospike exporter - new integtation
newrelic/newrelic-prometheus-exporters-packages pull request #131
Opened 2022-11-17 09:21 UTC by pkosanam

Description:
We are trying to integrate a new quickstart named "[Aerospike](https://aerospike.com/)"
Hence, I have created this PR to make sure that users can use nri-aerospike to install the aerospike-prometheus-exporter binary

Aerospike prometheus exporter: https://github.com/aerospike/aerospike-prometheus-exporter

2023-02-13 15:01 UTC, carlossscastro requested changes
Nice work so far!
We're almost there.
A few changes to make the E2E pass + a couple of other changes needed.
Some of the changes required were introduced by us when we implemented multi OS and Architecture support in the exporter packages.

2023-02-16 18:36 UTC, pkosanam commented
Thank you @carlossscastro , I have updated all the files as guided.

On executing make-test-e2e-aerospike \ ... \ ... on my local environment, I am seeing the below error but was able to capture metrics after few mins on one.newrelic.com

Is it common or is there any other configuration check which I am missing ?

Observing error while executing make-test-e2e command:
<img width="944" alt="image" src="https://user-images.githubusercontent.com/99316285/219456469-399414e4-287b-4a61-aa57-7ea1e509ac36.png">

Observing metrics on one.newrelic.com after few minutes:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/99316285/219456581-45b5d1ad-837c-4ec6-ad32-ea3c89da5312.png">

Thank you. 😃
cc: @mdumpati

2023-02-17 10:10 UTC, pkosanam commented on exporters/aerospike/ape.toml.tmpl
> +user = ""
I have added all the required fields on the /exporters/aerospike/aerospike.config.yml file and update the ape.toml.tmpl file accordingly.

Kindly update me if there is anything that I can change here. 😃

2023-02-17 10:11 UTC, pkosanam commented on exporters/aerospike/exporter.yml
> +exporter_config_files: ape.toml
added "package_linux_goarchs: amd64,arm64"

2023-02-17 10:12 UTC, pkosanam commented on exporters/aerospike/build-exporter-linux.sh
> +make
added.. 👍

2023-02-27 11:19 UTC, carlossscastro requested changes

2023-02-27 11:19 UTC, carlossscastro commented on exporters/aerospike/e2e/e2e_spec.yml
> +        - type: "AEROSPIKE_NODE"
According to the entity-definition (https://github.com/newrelic/entity-definitions/blob/main/definitions/ext-aerospike/definition.yml#L2) we only have an Entity `AEROSPIKE`, so you need to adjust the test to the correct entity name and remove `AEROSPIKE_NODE` and `AEROSPIKE_NAMESPACE`

2023-02-27 11:19 UTC, carlossscastro commented on exporters/aerospike/e2e/e2e_spec.yml
> +            - AEROSPIKE_NAMESPACE
This line can be removed also as we don't have `AEROSPIKE_NAMESPACE` entity

2023-02-27 11:21 UTC, carlossscastro commented
Regarding the pipeline error, could you refetch your fork and rebase. It should get rid of the E2E error.

2023-02-27 11:28 UTC, carlossscastro requested changes

2023-02-27 11:28 UTC, carlossscastro commented on exporters/aerospike/e2e/e2e_spec.yml
> +            - aerospike_namespace_cache_read_pct
All these metrics seem to be created by the test environment so they shouldn't be excluded

2023-02-27 15:39 UTC, pkosanam commented
I am closing this PR as I have created another PR for aerospike.
new PR: https://github.com/newrelic/newrelic-prometheus-exporters-packages/pull/163

2023-02-27 15:39 UTC, closed without merging